select top 10 * from customer;

--what is the total revenue generated by male vs.female customers?
select gender,avg(purchase_amount) as revenue
from customer
group by gender 

--which customers used dicount but still spent more then the average purchase amount
select customer_id,purchase_amount
from customer
where discount_applied='yes' and purchase_amount >
(select avg(purchase_amount)from customer)

--which are the top 5 products with the highest average review rathing
select top 5 item_purchased,avg(review_rating) as average_review_rating
from customer
group by item_purchased
order by (average_review_rating) desc

--compare the Average purchase amounts between standard and express shipping.
select shipping_type,
avg(purchase_amount)
from customer
where shipping_type in('Standard','Express')
group by shipping_type


-- Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
with customer_type as (
SELECT customer_id, previous_purchases,
CASE 
    WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
FROM customer)

select customer_segment,count(*) AS "Number of Customers" 
from customer_type 
group by customer_segment;

-- What are the top 3 most purchased products within each category? 
WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)
SELECT item_rank,category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <=3;
 
-- Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

--What is the revenue contribution of each age group? 
SELECT 
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue desc;

